### PR TITLE
Update Airspace.cpp

### PR DESCRIPTION
**Pull request by johnthomas22**
OTHER and MATZ are AC options in ASSelect

### CODE REVIEW

**Review by alus- — CHANGES_REQUESTED** [review]
Thank you for taking care also of those two other airspace types!
Anyway, sorry but, this pull request is incomplete: the two new categories should be first of all added also to the "Type" enum in the "Airspace" class otherwise the "Airspace::CategoryName()" will not work anymore.
And there should be also some code to parse and write those two new categories in OpenAir files otherwise it makes no sense to have them.

**Comment by johnthomas22** [comment]
Alberto,

I'm not really C++ competent. If you'd prefer to handle it yourself and
have time, I'll happily test it for you :-)

Regards,

John Thomas

**Comment by alus-** [comment]
OK then I will do it. No problem.
If you open a pull request I would think that you are willing to implement it. Otherwise the best option would be to just report an issue and if we will have time we will take care of it.

Question: those two extra airspace categories are used in OpenAir right?
Can you attach an example?

**Comment by johnthomas22** [comment]
Sorry, should have just raised an issue, I thought I'd give it a try, too
ambitious :-)


 uk2020-12-31.txt.orig
<https://drive.google.com/file/d/17mEamRzYloPM2_lodjgGPz6pU102684o/view?usp=drive_web>

Regards,

John Thomas

**Comment by alus-** [comment]
John, I appreciate your help, also because this highlighted that there are other improvements possible with OpenAir.
So this pull request is accepted and I will take care of doing the rest.

**Comment by johnthomas22** [comment]
Alberto,

I tried a fresh git clone, clean.sh, build.sh and install.sh. There is a
new executable, but I still get:

[image: image.png]

Have I done something wrong?

Regards,

John Thomas

**Comment by alus-** [comment]
Hi John,

sorry for responding only now, unfortunately I don't have that much free time.

I can't see here the image you tried to attach so therefore I don't know what went wrong.
Please consider also other places where similar programming questions may have already been asked (such as StackOverflow) in order to get a faster solution.

Best regards,

Alberto

**Comment by johnthomas22** [comment]
Alberto,

I know what you mean, though pretty quiet here in lockdown after the
holiday period. There's no urgency to this, it's just an experiment that
may possibly help some wannabe cross-country pilots with flight planning.

https://www.google.com/maps/d/u/0/edit?mid=1L8ssJmZH50s4fU4OfEMr6SDO78u9HJ1i&usp=sharing


These were the errors:

ERROR: unable to parse OpenAir line 512: AC MATZ
ERROR: unable to parse OpenAir line 519: AC MATZ
ERROR: unable to parse OpenAir line 531: AC MATZ
ERROR: unable to parse OpenAir line 543: AC MATZ
ERROR: unable to parse OpenAir line 1686: AC OTHER
ERROR: unable to parse OpenAir line 1693: AC OTHER
ERROR: unable to parse OpenAir line 1700: AC OTHER

I think what was missing are these lines.

        else if (length == 7 && line.substr(3) == "MATZ") type =
Airspace::MATZ; //Military ATZ
        else if (length == 8 && line.substr(3) == "OTHER") type =
Airspace::OTHER;

To save you time, I'll submit another pull request. You can either accept
it, and let me do the edit, or fix it yourself at your option.

C++ is like other foreign languages to me. I can just about read some
French and German, but not create a sentence myself :-)

The one remaining issue is Google Maps only allows ten layers. With MATZ
and OTHER, that's 11. Not sure how to deal with that.

Regards,

John Thomas

**Pull request merged**
